OUTPUT = = ../../gen/output

all:$(OUTPUT)/price_boxplotplot.pdf $(OUTPUT)/plot_price.pdf $(OUTPUT)/plot_price1.pdf


$(OUTPUT)/price_boxplotplot.pdf $(OUTPUT)/plot_price.pdf $(OUTPUT)/plot_price1.pdf: analyze.R
	R --vanilla < analyze.R